#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileRouterManagement.Views.Resource", IsApplication=true)]

namespace MobileRouterManagement.Views
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MobileRouterManagement.Core.Resource.String.ApplicationName = global::MobileRouterManagement.Views.Resource.String.ApplicationName;
			global::MobileRouterManagement.Core.Resource.String.Hello = global::MobileRouterManagement.Views.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050019
			public const int addNewRuleButton = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int addRuleDestinationIpEditText = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int addRuleDestinationPortEditText = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int addRuleEnabledCheckBox = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int addRuleNameEditText = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int addRuleSourceIpEditText = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int addRuleSourceMacEditText = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int addRuleSourcePortEditText = 2131034115;
			
			// aapt resource value: 0x7f050017
			public const int backWirelessButton = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int channelSpinner = 2131034131;
			
			// aapt resource value: 0x7f050032
			public const int channelTextView = 2131034162;
			
			// aapt resource value: 0x7f050023
			public const int closeButton = 2131034147;
			
			// aapt resource value: 0x7f05002d
			public const int deleteRuleButton = 2131034157;
			
			// aapt resource value: 0x7f050016
			public const int disabledCheckbox = 2131034134;
			
			// aapt resource value: 0x7f050035
			public const int disabledTextView = 2131034165;
			
			// aapt resource value: 0x7f05002e
			public const int editRuleButton = 2131034158;
			
			// aapt resource value: 0x7f05000d
			public const int editRuleDestinationIpEditText = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int editRuleDestinationPortEditText = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int editRuleEnabledCheckBox = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int editRuleNameEditText = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int editRuleSourceIpEditText = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int editRuleSourceMacEditText = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int editRuleSourcePortEditText = 2131034124;
			
			// aapt resource value: 0x7f050037
			public const int editWirelessButton = 2131034167;
			
			// aapt resource value: 0x7f050012
			public const int encryptionSpinner = 2131034130;
			
			// aapt resource value: 0x7f050031
			public const int encryptionTextView = 2131034161;
			
			// aapt resource value: 0x7f050007
			public const int exitEditRuleButton = 2131034119;
			
			// aapt resource value: 0x7f05002c
			public const int exitShowRuleButton = 2131034156;
			
			// aapt resource value: 0x7f050036
			public const int exitShowWirelessButton = 2131034166;
			
			// aapt resource value: 0x7f05001a
			public const int firewallListView = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int ipEditText = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int keyEditText = 2131034129;
			
			// aapt resource value: 0x7f050030
			public const int keyTextView = 2131034160;
			
			// aapt resource value: 0x7f050020
			public const int loadingPanel = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int loginAgainButton = 2131034146;
			
			// aapt resource value: 0x7f05001f
			public const int loginButton = 2131034143;
			
			// aapt resource value: 0x7f05001b
			public const int logoImageView = 2131034139;
			
			// aapt resource value: 0x7f050024
			public const int menuListView = 2131034148;
			
			// aapt resource value: 0x7f050014
			public const int modeSpinner = 2131034132;
			
			// aapt resource value: 0x7f050033
			public const int modeTextView = 2131034163;
			
			// aapt resource value: 0x7f050015
			public const int networkSpinner = 2131034133;
			
			// aapt resource value: 0x7f050034
			public const int networkTextView = 2131034164;
			
			// aapt resource value: 0x7f05001d
			public const int passwordEditText = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int saveButton = 2131034142;
			
			// aapt resource value: 0x7f050008
			public const int saveModifedRuleButton = 2131034120;
			
			// aapt resource value: 0x7f050018
			public const int saveWirelessButton = 2131034136;
			
			// aapt resource value: 0x7f050021
			public const int savedAccesDatasExpandlableListView = 2131034145;
			
			// aapt resource value: 0x7f050029
			public const int showRuleDestinationIpTextView = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int showRuleDestinationPortTextView = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int showRuleEnabledTextView = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int showRuleNameTextView = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int showRuleSourceIpTextView = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int showRuleSourceMacTextView = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int showRuleSourcePortTextView = 2131034152;
			
			// aapt resource value: 0x7f050010
			public const int ssidEditText = 2131034128;
			
			// aapt resource value: 0x7f05002f
			public const int ssidTextView = 2131034159;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddFirewallRule = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditFirewallRule = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditWireless = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Firewall = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Logout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ShowFirewallRule = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ShowWireless = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
